[package]
name = "kani"
version = "0.0.1"
authors = ["Totsugekitai <37617413+Totsugekitai@users.noreply.github.com>"]
edition = "2021"

[[bin]]
name = "kani"
path = "main.rs"

[dependencies]
x86_64 = "0.14.6"
spin = "0.9.2"