name: kani-ci

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUSTC_FORCE_INCREMENTAL: 1
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/cache_cargo
      - run: rustup install nightly
      - name: build kani OS
        run: make build-kernel
  fmt:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - run: rustup component add rustfmt
      - uses: ./.github/actions/cache_cargo
      - name: fmt
        run: cargo fmt --all -- --check
  clippy:
    runs-on: ubuntu-latest
    env:
      RUSTC_FORCE_INCREMENTAL: 1
    needs: build
    steps:
      - uses: actions/checkout@v3
      - run: rustup component add clippy
      - uses: ./.github/actions/cache_cargo
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
  # test:
  #   runs-on: ubuntu-latest
  #   env:
  #     RUSTC_FORCE_INCREMENTAL: 1
  #   needs: build
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: ./.github/actions/cache_cargo
  #     - name: test
  #       run: cargo test --all -- --nocapture
